### PR TITLE
fix: 's/astometry/astrometry/g'

### PR DESCRIPTION
**Pull request by gmacario**
Follow-up to https://github.com/Three-Buddy-Problem/exoplanet-quest-web/issues/1

### CODE REVIEW

**Comment by kaandesu** [comment]
Thank you so much for the PR! Before merging, if you don’t mind us asking—are we allowed to make changes like fixing typos or editing the README after the final submission? We weren’t sure, but we’d love to make these improvements if permitted.

**Comment by gmacario** [comment]
> Thank you so much for the PR! Before merging, if you don’t mind us asking—are we allowed to make changes like fixing typos or editing the README after the final submission? We weren’t sure, but we’d love to make these improvements if permitted.

Fair point!

I do not know either - also because I have only read through the rules of the *local* NASA Space Apps Challenge which happened yesterday at I3P, and whose awards have already been distributed, therefore I see no problems there.

For what concerns the *global* [2024 NASA Space Apps Challenge](https://www.spaceappschallenge.org/nasa-space-apps-2024/), as far as I know this is also closed now:

image

**Review by kaandesu — APPROVED** [review]

**Comment by gmacario** [comment]
@kaandesu I am afraid you were faster than me 😄 

I had prepared a new PR in https://github.com/Three-Buddy-Problem/exoplanet-quest-web/pull/5

Please notice that this original PR was against the *main* branch which I understand you did not want to modify...

**Comment by kaandesu** [comment]
I misclicked on this one instead and then had to revert the changes immediately. 😢

**Pull request merged**
